[package]
name = "ethersync"
description = "Enables real-time co-editing of local text files."
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1" }
jsonrpc-core = "18.0.0"
clap = { version = "4.5.3", features = ["derive"] }
automerge = "0.5.9"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
operational-transform = "0.6.1"
anyhow = "1.0.81"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console-subscriber = "0.2.0"
